version: 2
updates:
  # GitHub Actions (CI/CD workflows)
  - package-ecosystem: "github-actions"
    directory: "/"  # raíz del repo
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "actions"
      include: "scope"

  # Node.js (frontend o herramientas CLI)
  - package-ecosystem: "npm"
    directory: "/src/js"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
      include: "scope"

  # Python (auditorías, scripts, backend)
  - package-ecosystem: "pip"
    directory: "/src/py"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "pip"
      include: "scope"

  # Docker (contenedores de laboratorio o CI)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "docker"
      include: "scope"
