model:
  name: SimpleCNN
  input_channels: 3
  num_classes: 10

training:
  batch_size: 32
  epochs: 5
  learning_rate: 0.01
  optimizer: SGD
  loss_function: CrossEntropyLoss

dataset:
  name: FakeData
  transform:
    - ToTensor
    - Normalize: [0.5, 0.5]

# Licensed under the Apache License, Version 2.0 (2025)
# © Develop Aguascalientes & Copilot Microsoft

